package es.incidence.core.entity.event;

public enum  EventCode
{
    VEHICLE_ADDED,
    VEHICLE_UPDATED,
    VEHICLE_DELETED,
    VEHICLE_DRIVER_UPDATED,
    BEACON_ADDED,
    BEACON_UPDATED,
    BEACON_DELETED,
    USER_UPDATED,
    USER_LOCATION_UPDATED,
    INCIDENCE_REPORTED,

    APP_DID_BECOME_ACTIVE,
    APP_DID_RESIGN_ACTIVE,
    APP_WILL_RESIGN_ACTIVE,
    HOME_MENU_LOCK,
    HOME_MENU_UNLOCK,
    VOLUMEN_CHANGED,
    INCICENDE_TIME_CHANGED,
    INCICENDE_TIME_STOP,
    INCICENDE_VEHICLE_SELECTED
}
